### PR TITLE
spm_import: improve material transparency/shininess

### PR DESCRIPTION
**Pull request by scurest**
* Handle textures with transparency. If a texture has transparency is detected with `image.depth == 32` which isn't foolproof but usually works. The blend mode is set to "Alpha Hashed".
* Make materials less shiny by increasing the roughness and decreasing the specular. Looks closer to how the models look in STK.

Before / After :  
img

### CODE REVIEW

**Comment by RQWorldblender** [comment]
I think I'm going to need some help on how I can make use of `wrap.base_color_texture.texcoords = 'UV'`, because I'm trying to figure out the best way to set UV maps during creation. So far, I learned:
* To achieve the 2nd-image on top, I need to use a mix shader.
* The most optimal setting is to have 2 principled BSDF shaders, each linked to the images I want to use.
* As to where the UV maps come into play, I learned that I won't be assigning images directly to them anymore. Instead, I can use them as the vector setting to where the images are linked.
* For the mix shader itself, to affect the transparency, it has to be the image texture node linked to the 2nd shader.

**Comment by scurest** [comment]
I think `wrap.base_color_texture.texcoords = 'UV'` creates this thing

texco

If you want to retrieve the UVs from a specific UVMap (say the first one, which is named `UVMap`) you need this thing

uvmap

so you're going to have move outside what node_shader_utils can do for you.

**Comment by scurest** [comment]
Can you link me an .spm that uses two textures for testing?

**Comment by RQWorldblender** [comment]
Have you already checked out at least the stk-assets repository? That way, I don't have to keep linking you the files, and I can tell you where to look in your copy. The Cornfield Crossing track has a section the utilizes two textures, at the house with white wood. If you're not willing to do an svn checkout, here is the direct link to the track file: http://svn.code.sf.net/p/supertuxkart/code/stk-assets/tracks/cornfield_crossing/cornfield_crossing_track.spm

**Pull request merged**
